### ISSUE TITLE
GPU acceleration roadmap [WIP]

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomolibgpu#47]
The list of the modules that require code optimisation and GPU acceleration. Please approach them in the following priority order. 

- [x] [Normalisation](https://github.com/DiamondLightSource/httomolib/blob/contractors/src/httomolib/prep/normalize.py) module. Contains two implementations, CuPy [one](https://github.com/DiamondLightSource/httomolib/blob/08f92d3ef2f2eff5783045b739f646c7b28e2866/src/httomolib/prep/normalize.py#L129) and the [one](https://github.com/DiamondLightSource/httomolib/blob/08f92d3ef2f2eff5783045b739f646c7b28e2866/src/httomolib/prep/normalize.py#L33) using CUDA kernel. The latter produces the result different from the CuPy implementation and needs to be checked. Also the grid/block sizes affect the result as well. The input to the normalisation module is _uint16_ data type. 
- [x] [Median/dezinger](https://github.com/DiamondLightSource/httomolib/blob/08f92d3ef2f2eff5783045b739f646c7b28e2866/src/httomolib/misc/corr.py#L34) filter. The raw CUDA kernel has been ported from the [code](https://github.com/dkazanc/larix/blob/06f3952504dc97b84ec0688b6ab8dbdf1b6bdfc1/src/Core/GPU_modules/MedianFilt_GPU_core.cu#L101) in the [Larix](https://github.com/dkazanc/larix) toolbox. The code does compile, however the result is incorrect. For comparison one can use `scipy.ndimage.median_filter(np.float32(Input), size=3) ` . Arranging in the similar fashion using templates would be great. Block and grid sizes to be checked if [correct](https://github.com/DiamondLightSource/httomolib/blob/08f92d3ef2f2eff5783045b739f646c7b28e2866/src/httomolib/misc/corr.py#L135). The input to the median filter module is _uint16_ and _float32_ data type. 
- [x] [Centering](https://github.com/DiamondLightSource/httomolib/blob/contractors/src/httomolib/recon/rotation.py) module. Has got two methods in the file, the [one](https://github.com/DiamondLightSource/httomolib/blob/08f92d3ef2f2eff5783045b739f646c7b28e2866/src/httomolib/recon/rotation.py#L39) for the normal 180 degrees data and 360 degrees [one](https://github.com/DiamondLightSource/httomolib/blob/08f92d3ef2f2eff5783045b739f646c7b28e2866/src/httomolib/recon/rotation.py#L348). 
- [ ] [Distortion correction](https://github.com/DiamondLightSource/httomolib/blob/master/src/httomolib/prep/alignment.py#L169) module
- [x] [Stripes removal](https://github.com/DiamondLightSource/httomolib/blob/08f92d3ef2f2eff5783045b739f646c7b28e2866/src/httomolib/prep/stripe.py#L41) module
- [x] [Reconstruction](https://github.com/DiamondLightSource/httomolib/blob/contractors/src/httomolib/recon/algorithm.py) module.  Please check this CuPy code [here](https://github.com/DiamondLightSource/httomolib/blob/08f92d3ef2f2eff5783045b739f646c7b28e2866/src/httomolib/recon/algorithm.py#L115) that does the filtering, if it can be further optimised/accelerated.
- [x] [Phase retrieval ](https://github.com/DiamondLightSource/httomolib/blob/08f92d3ef2f2eff5783045b739f646c7b28e2866/src/httomolib/prep/phase.py#L259)module 

To run full pipelines with the series of the modules above please see the following [script](https://github.com/DiamondLightSource/httomolib/blob/contractors/examples/pipeline_preproc.py)

**Comment by yousefmoazzam** [comment]
An alternative raw CUDA kernel to perform normalisation has been added: https://github.com/DiamondLightSource/httomolib/blob/9ca14934e338028fdd3a10e72a4d58ccefc68bd9/src/httomolib/prep/normalize.py#L128-L234
which appears to replicate the implementation in `normalize_cupy()`; possibly could be useful for comparison purposes.
